######################################################### {COPYRIGHT-TOP} ###
# Licensed Materials - Property of IBM
# 5900-AEO
#
# Copyright IBM Corp. 2020, 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication, or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
######################################################### {COPYRIGHT-END} ###
apiVersion: v1
imagePullSecrets:
- name: ibm-entitlement-key
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: iaf-demo-cartridge-operator
  name: iaf-demo-cartridge-operator
